### ISSUE TITLE
Vim + Solarized sur Windows WSL

### ISSUE THREAD

**Issue by cybernar** [vjousse/vim-for-humans-book#16]
Bonjour Vincent, je suis en train de lire votre ouvrage sur vim.

J'utilise Windows 10 + WSL2 + Ubuntu 20.04, ce qui me permet d'avoir une vraie console Linux dans Windows. C'est génial mais comme il n'y a pas d'interface graphique, forcément il vaut mieux connaître vim ;)

Je vous signale cependant qu'avec la configuration de .vimrc proposée dans votre ouvrage, on obtient un fond gris clair qui pose problème pour la lisibilité. 

![capture_wsl_vim1](https://user-images.githubusercontent.com/5719742/200290593-42c1bb03-c3b1-491a-80af-c717deca8cad.png)

J'ai cherché un peu sur le net comment réparer cela, il semble qu'il faut régler le theme sur un mode 256 couleurs (si j'ai bien compris) : 

`let g:solarized_termcolors=256`

Voici ce que j'obtiens avec cette option.

![capture_wsl_vim2](https://user-images.githubusercontent.com/5719742/200290600-c0a09901-33ec-4701-a98b-15a3f86792e4.png)

Cyril

**Comment by cybernar** [comment]
J'ai rencontré un autre problème, cette fois avec **pathogen**, qui n'a pas fonctionné du 1er coup.
Quand je l'installe avec cette commande, il ne trouve pas le theme solarized ni la commande NERDTree :

`curl -so ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim`

Alors j'ai testé cette commande d'après le github de tpope, et là ça fonctionne :

`curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim`

Cyril

**Comment by cybernar** [comment]
Remarque : j'ai vim 8.0 dans ma console Ubuntu.

**Comment by vjousse** [comment]
Hello Cyril,
Tout d'abord merci pour tes retours. Je t'avoue que n'étant pas sous Windows et tout ça datant d'il y a quelques années maintenant, ta contribution est plus que la bienvenue !
Je vais prendre un peu de temps dans les prochains jours pour modifier ça. N'hésite pas si tu as d'autres retours.

**Comment by vjousse** [comment]
Je viens de commiter les modifications. Merci @cybernar !
