### ISSUE TITLE
Refactoring and basic IDE features

### ISSUE THREAD

**Issue by EmrysMyrddin** [vjousse/vim-for-humans-book#9]
This book is great to begin the use of Vim. But for coders, it lacks a final part wich gives some clues about how to transform our Vim into a real IDE with refactoring facilites and automatic error correction.

I mean, yes what you have shown to us here is a great tool for quick text editing, but it's not suitable for all days programming like intelliji or Eclipse are.

Is it something doable ?

**Comment by vjousse** [comment]
Well, I'm a coder and I'm using Vim on a daily basis without any problem.

Could you elaborate what "real IDE" means? You want something that "renames" your classes when you're refactoring and tells you when you have a typo or a compile problem in your file?

**Comment by EmrysMyrddin** [comment]
I know that some people are happy with Vim for coding, and I would like to be one of them ! I realy love the way you can navigate in a file with Vim but I can't push myself to use it for my code.

Yes, renaming classes is a good example. I have found some solutions with Find and Replace but it doesn't work well with renaming variables for example.

By error management I mean hint an automatic correction like Intelliji or Eclipse is able to do. For exemple, add a missing import, change the signature of a methode, you see what I meen ?

**Comment by vjousse** [comment]
Sure.

For the syntax check, the best tool around in my opinion is Syntastic: https://github.com/vim-syntastic/syntastic

I'm not aware of a generic tool for code refactoring as it's very dependant of the language you're using. What language do you want to be able to refactor?

**Comment by EmrysMyrddin** [comment]
I'm using lot of diferent languages but mainly it's Java, Scala, Javascript and Haskell. So I need refactoring for Java and Scala since it's less relevant in my opinion for Javascript and Haskell.

**Comment by EmrysMyrddin** [comment]
After some research, perhaps for my case the better is to use Intelliji with the Vim emulator plugin. It will allow me to have the navigation of vim and all the facilities offered by Intelliji...

It's not ideal since Vim plugin's are not supported and the navigation between file seems not very handy but I think that it's a good tradeoff.

**Comment by vince06fr** [comment]
maybe you can check this tutorial, I am not sure it is relevant for tour use case:
http://yannesposito.com/Scratch/en/blog/Vim-as-IDE/

**Comment by vjousse** [comment]
This is now out of scope for this book. Using neovim and distributions based on it like LazyVim is the way to go now http://www.lazyvim.org/
